# Generated by Django 4.2.1 on 2023-05-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('first_name', 'last_name', 'phone_number')},
        ),
    ]
