# Generated by Django 4.2.1 on 2023-05-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
