# Generated by Django 4.2.1 on 2023-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Nao Urgente', 'Nao Urgente')], default='Nao Urgente', max_length=20),
        ),
    ]
